In [ ]:
import requests

url = "https://datasets-server.huggingface.co/rows"

params = {
    "dataset": "bigbio/multi_xscience",
    "config": "multi_xscience_bigbio_t2t",
    "split": "train",
    "offset": 0,
    "length": 5
}

response = requests.get(url, params=params, timeout=60)
response.raise_for_status()

result = response.json()
rows = [item["row"] for item in result["rows"]]

print("Number of examples:", len(rows))
print("Columns:", list(rows[0].keys()))

for i, row in enumerate(rows[:2], start=1):
    print(f"\n--- Example {i} ---")
    print("Query paper:", str(row.get("text_1", ""))[:500])
    print("Reference papers:", str(row.get("text_2", ""))[:1000])

Number of examples: 5
Columns: ['id', 'document_id', 'text_1', 'text_2', 'text_1_name', 'text_2_name']

--- Example 1 ---
Query paper: Author(s): Kuperberg, Greg; Thurston, Dylan P. | Abstract: We give a purely topological definition of the perturbative quantum invariants of links and 3-manifolds associated with Chern-Simons field theory. Our definition is as close as possible to one given by Kontsevich. We will also establish some basic properties of these invariants, in particular that they are universally finite type with respect to algebraically split surgery and with respect to Torelli surgery. Torelli surgery is a mutual
Reference papers: This note is a sequel to our earlier paper of the same title [4] and describes invariants of rational homology 3-spheres associated to acyclic orthogonal local systems. Our work is in the spirit of the Axelrod–Singer papers [1], generalizes some of their results, and furnishes a new setting for the purely topological implications of their work. Recently, Mullins calculated the Casson-Walker invariant of the 2-fold cyclic branched cover of an oriented link in S^3 in terms of its Jones polynomial and its signature, under the assumption that the 2-fold branched cover is a rational homology 3-sphere. Using elementary principles, we provide a similar calculation for the general case. In addition, we calculate the LMO invariant of the p-fold branched cover of twisted knots in S^3 in terms of the Kontsevich integral of the knot.

--- Example 2 ---
Query paper: A statistical model for segmentation and word discovery in child directed speech is presented. An incremental unsupervised learning algorithm to infer word boundaries based on this model is described and results of empirical tests showing that the algorithm is competitive with other models that have been used for similar tasks are also presented.
Reference papers: This paper presents a model-based, unsupervised algorithm for recovering word boundaries in a natural-language text from which they have been deleted. The algorithm is derived from a probability model of the source that generated the text. The fundamental structure of the model is specified abstractly so that the detailed component models of phonology, word-order, and word frequency can be replaced in a modular fashion. The model yields a language-independent, prior probability distribution on all possible sequences of all possible words over a given alphabet, based on the assumption that the input was generated by concatenating words from a fixed but unknown lexicon. The model is unusual in that it treats the generation of a complete corpus, regardless of length, as a single event in the probability space. Accordingly, the algorithm does not estimate a probability distribution on wordss instead, it attempts to calculate the prior probabilities of various word sequences that could unde

In [ ]:
import re
import requests
from collections import Counter

url = "https://datasets-server.huggingface.co/rows"

params = {
    "dataset": "bigbio/multi_xscience",
    "config": "multi_xscience_bigbio_t2t",
    "split": "train",
    "offset": 0,
    "length": 20
}

response = requests.get(url, params=params, timeout=60)
response.raise_for_status()

rows = [item["row"] for item in response.json()["rows"]]

for i, row in enumerate(rows[:10], start=1):
    text = row.get("text_2", "")
    names = row.get("text_2_name", "")

    print(f"\nExample {i}")
    print("Reference metadata:", str(names)[:250])
    print("Reference text length:", len(text))
    print("Citation markers:", re.findall(r"\[\d+\]", text)[:15])
    print("Text preview:", text[:180].replace("\n", " "))

Example 1
Reference metadata: Cite abstracts
Reference text length: 833
Citation markers: ['[4]', '[1]']
Text preview: This note is a sequel to our earlier paper of the same title [4] and describes invariants of rational homology 3-spheres associated to acyclic orthogonal local systems. Our work is

Example 2
Reference metadata: Cite abstracts
Reference text length: 1296
Citation markers: []
Text preview: This paper presents a model-based, unsupervised algorithm for recovering word boundaries in a natural-language text from which they have been deleted. The algorithm is derived from

Example 3
Reference metadata: Cite abstracts
Reference text length: 547
Citation markers: []
Text preview: It is well known that any planar graph contains at most O(n) complete subgraphs. We extend this to an exact characterization: G occurs O(n) times as a subgraph of any planar graph,

Example 4
Reference metadata: Cite abstracts
Reference text length: 447
Citation markers: []
Text preview: A historical review of spinors is given together with a construction of spinor spaces as minimal left ideals of Clifford algebras. Spinor spaces of euclidean spaces over reals have

Example 5
Reference metadata: Cite abstracts
Reference text length: 807
Citation markers: []
Text preview: Abstract : This thesis investigates adaptive compiler systems that perform, during program execution, code optimizations based on the dynamic behavior of the program as opposed to

Example 6
Reference metadata: Cite abstracts
Reference text length: 6083
Citation markers: []
Text preview: Despite the apparent success of the Java Virtual Machine, its lackluster performance makes it ill-suited for many speed-critical applications. Although the latest just-in-time comp

Example 7
Reference metadata: Cite abstracts
Reference text length: 7483
Citation markers: []
Text preview: Polymorphic inline caches (PICs) provide a new way to reduce the overhead of polymorphic message sends by extending inline caches to include more than one cached lookup result per

Example 8
Reference metadata: Cite abstracts
Reference text length: 1454
Citation markers: []
Text preview: This paper describes the motivations and strategies behind our group’s efforts to integrate the Tcl and Java programming languages. From the Java perspective, we wish to create a p

Example 9
Reference metadata: Cite abstracts
Reference text length: 1357
Citation markers: []
Text preview: Abstract The strong coupling dynamics of string theories in dimension d ⩾ 4 are studied. It is argued, among other things, that eleven-dimensional supergravity arises as a low ener

Example 10
Reference metadata: Cite abstracts
Reference text length: 1100
Citation markers: []
Text preview: Abstract The Bekenstein-Hawking area-entropy relation S BH = A 4 is derived for a class of five-dimensional extremal black holes in string theory by counting the degeneracy of BPS

In [ ]:
import requests
import json

url = "https://datasets-server.huggingface.co/rows"

params = {
    "dataset": "bigbio/multi_xscience",
    "config": "multi_xscience_bigbio_t2t",
    "split": "train",
    "offset": 0,
    "length": 1
}

response = requests.get(url, params=params, timeout=60)
response.raise_for_status()

example = response.json()["rows"][0]["row"]

print("All fields:")
for key, value in example.items():
    print(f"\n{key}:")
    print("Type:", type(value).__name__)
    print("Value:", repr(value)[:1000])

All fields:

id:
Type: str
Value: '1'

document_id:
Type: str
Value: '0'

text_1:
Type: str
Value: 'Author(s): Kuperberg, Greg; Thurston, Dylan P. | Abstract: We give a purely topological definition of the perturbative quantum invariants of links and 3-manifolds associated with Chern-Simons field theory. Our definition is as close as possible to one given by Kontsevich. We will also establish some basic properties of these invariants, in particular that they are universally finite type with respect to algebraically split surgery and with respect to Torelli surgery. Torelli surgery is a mutual generalization of blink surgery of Garoufalidis and Levine and clasper surgery of Habiro.'

text_2:
Type: str
Value: 'This note is a sequel to our earlier paper of the same title [4] and describes invariants of rational homology 3-spheres associated to acyclic orthogonal local systems. Our work is in the spirit of the Axelrod–Singer papers [1], generalizes some of their results, and furnishes a new setting for the purely topological implications of their work. Recently, Mullins calculated the Casson-Walker invariant of the 2-fold cyclic branched cover of an oriented link in S^3 in terms of its Jones polynomial and its signature, under the assumption that the 2-fold branched cover is a rational homology 3-sphere. Using elementary principles, we provide a similar calculation for the general case. In addition, we calculate the LMO invariant of the p-fold branched cover of twisted knots in S^3 in terms of the Kontsevich integral of the knot.'

text_1_name:
Type: str
Value: 'Abstract of query paper'

text_2_name:
Type: str
Value: 'Cite abstracts'

In [ ]:
import requests

url = "https://datasets-server.huggingface.co/parquet"

params = {
    "dataset": "bigbio/multi_xscience"
}

response = requests.get(url, params=params, timeout=60)
print("Status:", response.status_code)
response.raise_for_status()

data = response.json()

for item in data.get("parquet_files", []):
    print(
        "Config:", item.get("config"),
        "| Split:", item.get("split"),
        "| URL:", item.get("url")
    )

Status: 200
Config: multi_xscience_bigbio_t2t | Split: test | URL: https://huggingface.co/datasets/bigbio/multi_xscience/resolve/refs%2Fconvert%2Fparquet/multi_xscience_bigbio_t2t/test/0000.parquet
Config: multi_xscience_bigbio_t2t | Split: train | URL: https://huggingface.co/datasets/bigbio/multi_xscience/resolve/refs%2Fconvert%2Fparquet/multi_xscience_bigbio_t2t/train/0000.parquet
Config: multi_xscience_bigbio_t2t | Split: validation | URL: https://huggingface.co/datasets/bigbio/multi_xscience/resolve/refs%2Fconvert%2Fparquet/multi_xscience_bigbio_t2t/validation/0000.parquet
Config: multi_xscience_source | Split: test | URL: https://huggingface.co/datasets/bigbio/multi_xscience/resolve/refs%2Fconvert%2Fparquet/multi_xscience_source/test/0000.parquet
Config: multi_xscience_source | Split: train | URL: https://huggingface.co/datasets/bigbio/multi_xscience/resolve/refs%2Fconvert%2Fparquet/multi_xscience_source/train/0000.parquet
Config: multi_xscience_source | Split: validation | URL: https://huggingface.co/datasets/bigbio/multi_xscience/resolve/refs%2Fconvert%2Fparquet/multi_xscience_source/validation/0000.parquet

In [ ]:
import requests

url = "https://datasets-server.huggingface.co/rows"

params = {
    "dataset": "bigbio/multi_xscience",
    "config": "multi_xscience_source",
    "split": "train",
    "offset": 0,
    "length": 2
}

response = requests.get(url, params=params, timeout=60)

print("Status:", response.status_code)
response.raise_for_status()

data = response.json()
rows = [item["row"] for item in data["rows"]]

print("\nColumns:", list(rows[0].keys()))

for i, row in enumerate(rows, start=1):
    print(f"\n--- Source example {i} ---")
    for key, value in row.items():
        print(f"\n{key} ({type(value).__name__}):")
        print(repr(value)[:1500])

Status: 200

Columns: ['aid', 'mid', 'abstract', 'ref_abstract']

--- Source example 1 ---

aid (str):
'math9912167'

mid (str):
'1631980677'

abstract (str):
'Author(s): Kuperberg, Greg; Thurston, Dylan P. | Abstract: We give a purely topological definition of the perturbative quantum invariants of links and 3-manifolds associated with Chern-Simons field theory. Our definition is as close as possible to one given by Kontsevich. We will also establish some basic properties of these invariants, in particular that they are universally finite type with respect to algebraically split surgery and with respect to Torelli surgery. Torelli surgery is a mutual generalization of blink surgery of Garoufalidis and Levine and clasper surgery of Habiro.'

ref_abstract (dict):
{'mid': ['1481005306', '1641082372'], 'abstract': ['This note is a sequel to our earlier paper of the same title [4] and describes invariants of rational homology 3-spheres associated to acyclic orthogonal local systems. Our work is in the spirit of the Axelrod–Singer papers [1], generalizes some of their results, and furnishes a new setting for the purely topological implications of their work.', 'Recently, Mullins calculated the Casson-Walker invariant of the 2-fold cyclic branched cover of an oriented link in S^3 in terms of its Jones polynomial and its signature, under the assumption that the 2-fold branched cover is a rational homology 3-sphere. Using elementary principles, we provide a similar calculation for the general case. In addition, we calculate the LMO invariant of the p-fold branched cover of twisted knots in S^3 in terms of the Kontsevich integral of the knot.']}

--- Source example 2 ---

aid (str):
'cs9910011'

mid (str):
'2168463568'

abstract (str):
'A statistical model for segmentation and word discovery in child directed speech is presented. An incremental unsupervised learning algorithm to infer word boundaries based on this model is described and results of empirical tests showing that the algorithm is competitive with other models that have been used for similar tasks are also presented.'

ref_abstract (dict):
{'mid': ['2074546930'], 'abstract': ['This paper presents a model-based, unsupervised algorithm for recovering word boundaries in a natural-language text from which they have been deleted. The algorithm is derived from a probability model of the source that generated the text. The fundamental structure of the model is specified abstractly so that the detailed component models of phonology, word-order, and word frequency can be replaced in a modular fashion. The model yields a language-independent, prior probability distribution on all possible sequences of all possible words over a given alphabet, based on the assumption that the input was generated by concatenating words from a fixed but unknown lexicon. The model is unusual in that it treats the generation of a complete corpus, regardless of length, as a single event in the probability space. Accordingly, the algorithm does not estimate a probability distribution on wordss instead, it attempts to calculate the prior probabilities of various word sequences that could underlie the observed text. Experiments on phonemic transcripts of spontaneous speech by parents to young children suggest that our algorithm is more effective than other proposed algorithms, at least when utterance boundaries are given and the text includes a substantial number of short utterances.']}

In [ ]:
import requests
from collections import Counter

BASE_URL = "https://datasets-server.huggingface.co/rows"
DATASET = "bigbio/multi_xscience"
CONFIG = "multi_xscience_source"

def fetch_rows(split, offset, length=100):
    response = requests.get(
        BASE_URL,
        params={
            "dataset": DATASET,
            "config": CONFIG,
            "split": split,
            "offset": offset,
            "length": length
        },
        timeout=60
    )
    response.raise_for_status()
    return [item["row"] for item in response.json()["rows"]]

counts = Counter()
eligible = []
batch_size = 100
limit = 1000

for offset in range(0, limit, batch_size):
    batch = fetch_rows("train", offset, batch_size)

    for row in batch:
        refs = row.get("ref_abstract", {})
        abstracts = refs.get("abstract", []) if isinstance(refs, dict) else []

        n_refs = len(abstracts)
        counts[n_refs] += 1

        if n_refs in (3, 4):
            eligible.append({
                "paper_id": row["aid"],
                "input_abstract": row["abstract"],
                "reference_abstracts": abstracts
            })

print("Records inspected:", sum(counts.values()))
print("Reference-count distribution:", dict(sorted(counts.items())))
print("Examples with 3–4 references:", len(eligible))

if eligible:
    print("\nSample paper ID:", eligible[0]["paper_id"])
    print("Reference count:", len(eligible[0]["reference_abstracts"]))
    print("Input abstract:", eligible[0]["input_abstract"][:300])
    print("First reference:", eligible[0]["reference_abstracts"][0][:300])

Records inspected: 1000
Reference-count distribution: {1: 262, 2: 142, 3: 166, 4: 99, 5: 60, 6: 71, 7: 40, 8: 32, 9: 28, 10: 28, 11: 19, 12: 12, 13: 14, 14: 7, 15: 5, 16: 2, 17: 6, 18: 2, 19: 2, 20: 3}
Examples with 3–4 references: 265

Sample paper ID: cs9903018
Reference count: 3
Input abstract: Scripting languages are becoming more and more important as a tool for software development, as they provide great flexibility for rapid prototyping and for configuring componentware applications. In this paper we present LuaJava, a scripting tool for Java. LuaJava adopts Lua, a dynamically typed in
First reference: This paper describes the motivations and strategies behind our group’s efforts to integrate the Tcl and Java programming languages. From the Java perspective, we wish to create a powerful scripting solution for Java applications and operating environments. From the Tcl perspective, we want to allow

In [ ]:
import requests

url = "https://datasets-server.huggingface.co/rows"

params = {
    "dataset": "allenai/multixscience_dense_max",
    "config": "default",
    "split": "train",
    "offset": 0,
    "length": 2
}

response = requests.get(url, params=params, timeout=60)

print("Status:", response.status_code)

if response.ok:
    rows = [item["row"] for item in response.json()["rows"]]

    print("Columns:", list(rows[0].keys()))

    for key, value in rows[0].items():
        print(f"\n{key} ({type(value).__name__}):")
        print(repr(value)[:800])
else:
    print(response.text[:1500])

Status: 200
Columns: ['aid', 'mid', 'abstract', 'related_work', 'ref_abstract']

aid (str):
'math9912167'

mid (str):
'1631980677'

abstract (str):
'Author(s): Kuperberg, Greg; Thurston, Dylan P. | Abstract: We give a purely topological definition of the perturbative quantum invariants of links and 3-manifolds associated with Chern-Simons field theory. Our definition is as close as possible to one given by Kontsevich. We will also establish some basic properties of these invariants, in particular that they are universally finite type with respect to algebraically split surgery and with respect to Torelli surgery. Torelli surgery is a mutual generalization of blink surgery of Garoufalidis and Levine and clasper surgery of Habiro.'

related_work (str):
'Two other generalizations that can be considered are invariants of graphs in 3-manifolds, and invariants associated to other flat connections @cite_16 . We will analyze these in future work. Among other things, there should be a general relation between flat bundles and links in 3-manifolds on the one hand and finite covers and branched covers on the other hand @cite_26 .'

ref_abstract (dict):
{'cite_N': ['@cite_16', '@cite_26'], 'mid': ['1481005306', '1641082372'], 'abstract': ['This note is a sequel to our earlier paper of the same title [4] and describes invariants of rational homology 3-spheres associated to acyclic orthogonal local systems. Our work is in the spirit of the Axelrod–Singer papers [1], generalizes some of their results, and furnishes a new setting for the purely topological implications of their work.', 'Recently, Mullins calculated the Casson-Walker invariant of the 2-fold cyclic branched cover of an oriented link in S^3 in terms of its Jones polynomial and its signature, under the assumption that the 2-fold branched cover is a rational homology 3-sphere. Using elementary principles, we provide a similar calculation for the general case. In addition, we calcu

In [ ]:
import requests
import json
import time

BASE_URL = "https://datasets-server.huggingface.co/rows"
DATASET = "allenai/multixscience_dense_max"
CONFIG = "default"

def fetch_batch(split, offset, length=100):
    response = requests.get(
        BASE_URL,
        params={
            "dataset": DATASET,
            "config": CONFIG,
            "split": split,
            "offset": offset,
            "length": length
        },
        timeout=60
    )
    response.raise_for_status()
    return [x["row"] for x in response.json()["rows"]]

train_examples = []
offset = 0
target_examples = 1000
max_records = 10000
batch_size = 100

while offset < max_records and len(train_examples) < target_examples:
    rows = fetch_batch("train", offset, batch_size)
    if not rows:
        break

    for row in rows:
        refs = row.get("ref_abstract", {})
        ref_abstracts = refs.get("abstract", []) if isinstance(refs, dict) else []

        if len(ref_abstracts) not in (3, 4):
            continue

        related_work = row.get("related_work", "").strip()
        query_abstract = row.get("abstract", "").strip()

        if not query_abstract or not related_work:
            continue

        train_examples.append({
            "paper_id": row.get("aid", ""),
            "input_abstract": query_abstract,
            "reference_abstracts": ref_abstracts,
            "target_related_work": related_work
        })

    offset += len(rows)
    print(
        f"Inspected {offset} records | "
        f"Eligible examples: {len(train_examples)}"
    )

    time.sleep(0.2)

with open("/content/paperpilot_train.jsonl", "w", encoding="utf-8") as f:
    for example in train_examples:
        f.write(json.dumps(example, ensure_ascii=False) + "\n")

print("\nSaved examples:", len(train_examples))
print("File: /content/paperpilot_train.jsonl")

if train_examples:
    sample = train_examples[0]
    print("\nReference count:", len(sample["reference_abstracts"]))
    print("Target preview:", sample["target_related_work"][:500])

Inspected 100 records | Eligible examples: 25
Inspected 200 records | Eligible examples: 52
Inspected 300 records | Eligible examples: 85
Inspected 400 records | Eligible examples: 98
Inspected 500 records | Eligible examples: 120
Inspected 600 records | Eligible examples: 151
Inspected 700 records | Eligible examples: 169
Inspected 800 records | Eligible examples: 197
Inspected 900 records | Eligible examples: 231
Inspected 1000 records | Eligible examples: 265
Inspected 1100 records | Eligible examples: 296
Inspected 1200 records | Eligible examples: 318
Inspected 1300 records | Eligible examples: 345
Inspected 1400 records | Eligible examples: 371
Inspected 1500 records | Eligible examples: 398
Inspected 1600 records | Eligible examples: 424
Inspected 1700 records | Eligible examples: 448
Inspected 1800 records | Eligible examples: 478
Inspected 1900 records | Eligible examples: 509
Inspected 2000 records | Eligible examples: 542
Inspected 2100 records | Eligible examples: 578
Inspected 2200 records | Eligible examples: 602
Inspected 2300 records | Eligible examples: 632
Inspected 2400 records | Eligible examples: 654
Inspected 2500 records | Eligible examples: 683
Inspected 2600 records | Eligible examples: 705
Inspected 2700 records | Eligible examples: 729
Inspected 2800 records | Eligible examples: 752
Inspected 2900 records | Eligible examples: 777
Inspected 3000 records | Eligible examples: 797
Inspected 3100 records | Eligible examples: 828
Inspected 3200 records | Eligible examples: 856
Inspected 3300 records | Eligible examples: 882
Inspected 3400 records | Eligible examples: 907
Inspected 3500 records | Eligible examples: 935
Inspected 3600 records | Eligible examples: 965

HTTPError: 429 Client Error: Too Many Requests for url: https://datasets-server.huggingface.co/rows?dataset=allenai%2Fmultixscience_dense_max&config=default&split=train&offset=3600&length=100

In [ ]:
import json
import os

output_path = "/content/paperpilot_train.jsonl"

with open(output_path, "w", encoding="utf-8") as f:
    for example in train_examples:
        f.write(json.dumps(example, ensure_ascii=False) + "\n")

print("Saved examples:", len(train_examples))
print("File size:", round(os.path.getsize(output_path) / 1024, 2), "KB")
print("Saved to:", output_path)

Saved examples: 965
File size: 4911.32 KB
Saved to: /content/paperpilot_train.jsonl

In [ ]:
from google.colab import drive
drive.mount("/content/drive")

import shutil
import os

backup_dir = "/content/drive/MyDrive/PaperPilot"
os.makedirs(backup_dir, exist_ok=True)

shutil.copy2(
    "/content/paperpilot_train.jsonl",
    f"{backup_dir}/paperpilot_train.jsonl"
)

print("Backup saved to Google Drive:", backup_dir)

Mounted at /content/drive
Backup saved to Google Drive: /content/drive/MyDrive/PaperPilot

In [ ]:
import json
import random
import os

# 1. Remove invalid examples and duplicate paper IDs
cleaned = []
seen_ids = set()

for ex in train_examples:
    paper_id = ex.get("paper_id")
    input_text = ex.get("input_abstract", "").strip()
    target_text = ex.get("target_related_work", "").strip()
    refs = ex.get("reference_abstracts", [])

    if not paper_id or not input_text or not target_text:
        continue

    if not isinstance(refs, list) or len(refs) not in (3, 4):
        continue

    if any(not isinstance(r, str) or not r.strip() for r in refs):
        continue

    if paper_id in seen_ids:
        continue

    seen_ids.add(paper_id)

    cleaned.append({
        "paper_id": paper_id,
        "input_abstract": input_text,
        "reference_abstracts": refs,
        "target_related_work": target_text
    })

# 2. Shuffle reproducibly
random.Random(42).shuffle(cleaned)

# 3. Split 90% train / 10% validation
split_index = int(len(cleaned) * 0.9)
train_split = cleaned[:split_index]
val_split = cleaned[split_index:]

# 4. Save separate JSONL files
os.makedirs("/content/paperpilot_data", exist_ok=True)

def save_jsonl(data, path):
    with open(path, "w", encoding="utf-8") as f:
        for item in data:
            f.write(json.dumps(item, ensure_ascii=False) + "\n")

save_jsonl(train_split, "/content/paperpilot_data/train.jsonl")
save_jsonl(val_split, "/content/paperpilot_data/validation.jsonl")

print("Original examples:", len(train_examples))
print("Clean examples:", len(cleaned))
print("Training examples:", len(train_split))
print("Validation examples:", len(val_split))
print("Training file size (KB):",
      round(os.path.getsize("/content/paperpilot_data/train.jsonl") / 1024, 2))
print("Validation file size (KB):",
      round(os.path.getsize("/content/paperpilot_data/validation.jsonl") / 1024, 2))

if train_split:
    print("\nExample reference count:", len(train_split[0]["reference_abstracts"]))
    print("Target preview:", train_split[0]["target_related_work"][:400])

Original examples: 965
Clean examples: 439
Training examples: 395
Validation examples: 44
Training file size (KB): 2176.98
Validation file size (KB): 256.79

Example reference count: 3
Target preview: Recently, deep learning based methods @cite_6 @cite_1 have been proposed to address face anti-spoofing. They use CNNs to learn highly discriminative representations by taking face anti-spoofing as a binary classification problem. However, most of them easily suffer overfitting. Current publicly available face anti-spoofing datasets are too limited to cover various potential spoofing types. A very

In [ ]:
from collections import Counter, defaultdict

id_counts = Counter(
    ex.get("paper_id")
    for ex in train_examples
    if ex.get("paper_id")
)

groups = defaultdict(list)
for ex in train_examples:
    groups[ex.get("paper_id")].append(ex)

duplicate_ids = {
    pid: items for pid, items in groups.items()
    if pid and len(items) > 1
}

exact_duplicate_pairs = 0
same_id_different_targets = 0

for pid, items in duplicate_ids.items():
    pairs = {
        (item.get("input_abstract", ""), item.get("target_related_work", ""))
        for item in items
    }

    if len(pairs) == 1:
        exact_duplicate_pairs += len(items) - 1
    else:
        same_id_different_targets += 1

print("Collected examples:", len(train_examples))
print("Unique paper IDs:", len(id_counts))
print("IDs occurring multiple times:", len(duplicate_ids))
print("Extra rows with identical input and target:", exact_duplicate_pairs)
print("IDs with different input/target pairs:", same_id_different_targets)

print("\nExamples of repeated IDs:")
shown = 0

for pid, items in duplicate_ids.items():
    print(f"\nPaper ID: {pid} | Rows: {len(items)}")

    for item in items[:2]:
        print("Input:", item.get("input_abstract", "")[:160])
        print("Target:", item.get("target_related_work", "")[:160])

    shown += 1
    if shown == 3:
        break

Collected examples: 965
Unique paper IDs: 669
IDs occurring multiple times: 217
Extra rows with identical input and target: 0
IDs with different input/target pairs: 217

Examples of repeated IDs:

Paper ID: hep-th9807171 | Rows: 5
Input: The thesis begins with an introduction to M-theory (at a graduate student's level), starting from perturbative string theory and proceeding to dualities, D-bran
Target: The main objective of this chapter was to study the basic @math -branes that one encounters in M-theory, and to treat them in a unified way. The need to unify t
Input: The thesis begins with an introduction to M-theory (at a graduate student's level), starting from perturbative string theory and proceeding to dualities, D-bran
Target: Some of the intersection rules intersectionrules point towards an M-theory interpretation in terms of open branes ending on other branes. This idea will be elab

Paper ID: 1903.05454 | Rows: 2
Input: In this work, we present a camera geopositioning system based on matching a query image against a database with panoramic images. For matching, our system uses
Target: Convolutional features extracted from the deep layers of CNNs have shown great utility when addressing image matching and retrieval problems. Babenko @cite_10 e
Input: In this work, we present a camera geopositioning system based on matching a query image against a database with panoramic images. For matching, our system uses
Target: The problem of geopositioning can be seen as a dedicated branch of image retrieval. In this case, the objective is to compute extrinsic parameters (or coordinat

Paper ID: 1908.11829 | Rows: 2
Input: We consider the minimum cut problem in undirected, weighted graphs. We give a simple algorithm to find a minimum cut that @math -respects (cuts two edges of) a
Target: On an unweighted graph, Gabow @cite_13 showed how to compute the minimum cut in @math time, where @math is the capacity of the minimum cut. Karger @cite_29 impr
Input: We consider the minimum cut problem in undirected, weighted graphs. We give a simple algorithm to find a minimum cut that @math -respects (cuts two edges of) a
Target: A recent development uses low-conductance cuts to find the minimum cut in an undirected unweighted graph. This technique was introduced by Kawarabayashi and Tho

In [ ]:
import json
import os
import random
import hashlib
from collections import defaultdict

# 1. Validate and deduplicate complete examples
cleaned = []
seen_examples = set()

for ex in train_examples:
    paper_id = ex.get("paper_id")
    input_text = ex.get("input_abstract", "").strip()
    target_text = ex.get("target_related_work", "").strip()
    refs = ex.get("reference_abstracts", [])

    if not paper_id or not input_text or not target_text:
        continue

    if not isinstance(refs, list) or len(refs) not in (3, 4):
        continue

    refs = [r.strip() for r in refs if isinstance(r, str) and r.strip()]

    if len(refs) not in (3, 4):
        continue

    # Deduplicate by the complete training example, not paper ID
    fingerprint = hashlib.sha256(
        json.dumps(
            [input_text, refs, target_text],
            ensure_ascii=False
        ).encode("utf-8")
    ).hexdigest()

    if fingerprint in seen_examples:
        continue

    seen_examples.add(fingerprint)

    cleaned.append({
        "paper_id": str(paper_id),
        "input_abstract": input_text,
        "reference_abstracts": refs,
        "target_related_work": target_text
    })

# 2. Group all examples from the same paper
groups = defaultdict(list)

for ex in cleaned:
    groups[ex["paper_id"]].append(ex)

paper_ids = list(groups.keys())
random.Random(42).shuffle(paper_ids)

# Assign entire papers to one split
target_val_papers = max(1, round(len(paper_ids) * 0.10))
val_paper_ids = set(paper_ids[:target_val_papers])

train_split = [
    ex for pid, items in groups.items()
    if pid not in val_paper_ids
    for ex in items
]

val_split = [
    ex for pid, items in groups.items()
    if pid in val_paper_ids
    for ex in items
]

# 3. Save corrected datasets
output_dir = "/content/paperpilot_data_v2"
os.makedirs(output_dir, exist_ok=True)

def save_jsonl(data, path):
    with open(path, "w", encoding="utf-8") as f:
        for item in data:
            f.write(json.dumps(item, ensure_ascii=False) + "\n")

save_jsonl(train_split, f"{output_dir}/train.jsonl")
save_jsonl(val_split, f"{output_dir}/validation.jsonl")

train_ids = {ex["paper_id"] for ex in train_split}
val_ids = {ex["paper_id"] for ex in val_split}

print("Collected examples:", len(train_examples))
print("Valid unique examples:", len(cleaned))
print("Unique papers:", len(paper_ids))
print("Training examples:", len(train_split))
print("Validation examples:", len(val_split))
print("Paper-ID overlap:", len(train_ids & val_ids))
print("Saved to:", output_dir)

Collected examples: 965
Valid unique examples: 726
Unique papers: 541
Training examples: 652
Validation examples: 74
Paper-ID overlap: 0
Saved to: /content/paperpilot_data_v2

In [ ]:
import json
import numpy as np

train_path = "/content/paperpilot_data_v2/train.jsonl"
val_path = "/content/paperpilot_data_v2/validation.jsonl"

def load_jsonl(path):
    with open(path, encoding="utf-8") as f:
        return [json.loads(line) for line in f if line.strip()]

train_data = load_jsonl(train_path)
val_data = load_jsonl(val_path)

def approximate_tokens(text):
    # Rough estimate only; the model tokenizer will give exact counts.
    return len(text.split())

def report_lengths(name, data):
    input_lengths = []
    target_lengths = []

    for ex in data:
        refs = ex["reference_abstracts"]
        input_text = (
            "Write a related-work section based on these papers.\n"
            "Query paper:\n" + ex["input_abstract"] +
            "\nReference papers:\n" +
            "\n".join(f"[Paper {i+1}] {r}" for i, r in enumerate(refs))
        )

        input_lengths.append(approximate_tokens(input_text))
        target_lengths.append(
            approximate_tokens(ex["target_related_work"])
        )

    print(f"\n{name}: {len(data)} examples")

    for label, values in [
        ("Input words", input_lengths),
        ("Target words", target_lengths)
    ]:
        print(
            f"{label}: median={int(np.median(values))}, "
            f"90th percentile={int(np.percentile(values, 90))}, "
            f"maximum={max(values)}"
        )

report_lengths("Training", train_data)
report_lengths("Validation", val_data)

Training: 652 examples
Input words: median=706, 90th percentile=911, maximum=1277
Target words: median=109, 90th percentile=168, maximum=199

Validation: 74 examples
Input words: median=707, 90th percentile=923, maximum=1122
Target words: median=103, 90th percentile=166, maximum=191

In [ ]:
!pip -q install transformers

from transformers import AutoTokenizer
import numpy as np

MODEL_NAME = "Qwen/Qwen2.5-0.5B-Instruct"
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)

def make_messages(ex):
    refs = "\n\n".join(
        f"Reference Paper {i+1}:\n{ref}"
        for i, ref in enumerate(ex["reference_abstracts"])
    )

    user_prompt = f"""Write a coherent related-work section using the supplied papers.
Synthesize relevant ideas, methods, and relationships. Do not invent facts.

Query Paper Abstract:
{ex['input_abstract']}

Reference Paper Abstracts:
{refs}"""

    return [
        {
            "role": "system",
            "content": "You are a careful scientific literature-review assistant."
        },
        {"role": "user", "content": user_prompt},
        {"role": "assistant", "content": ex["target_related_work"]}
    ]

lengths = []

for ex in train_data + val_data:
    messages = make_messages(ex)
    token_ids = tokenizer.apply_chat_template(
        messages,
        tokenize=True,
        add_generation_prompt=False
    )
    lengths.append(len(token_ids))

print("Tokenizer:", MODEL_NAME)
print("Total examples:", len(lengths))
print("Median tokens:", int(np.median(lengths)))
print("90th percentile:", int(np.percentile(lengths, 90)))
print("95th percentile:", int(np.percentile(lengths, 95)))
print("Maximum tokens:", max(lengths))

for limit in [1024, 1536, 2048]:
    truncated = sum(length > limit for length in lengths)
    print(f"Exceeding {limit} tokens: {truncated}/{len(lengths)}")

config.json:   0%|          | 0.00/659 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/7.30k [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/2.78M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/1.67M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/7.03M [00:00<?, ?B/s]

Tokenizer: Qwen/Qwen2.5-0.5B-Instruct
Total examples: 726
Median tokens: 2
90th percentile: 2
95th percentile: 2
Maximum tokens: 2
Exceeding 1024 tokens: 0/726
Exceeding 1536 tokens: 0/726
Exceeding 2048 tokens: 0/726

In [ ]:
import numpy as np

def count_chat_tokens(ex):
    messages = make_messages(ex)

    encoded = tokenizer.apply_chat_template(
        messages,
        tokenize=True,
        add_generation_prompt=False,
        return_dict=True
    )

    # Count actual token IDs, not dictionary keys
    input_ids = encoded["input_ids"]

    if hasattr(input_ids, "shape"):
        return int(input_ids.shape[-1])

    # Handle either a flat list or a batch of token lists
    if input_ids and isinstance(input_ids[0], list):
        return len(input_ids[0])

    return len(input_ids)


# First inspect one example
sample_count = count_chat_tokens(train_data[0])
print("Tokens in one example:", sample_count)

# Then measure the full dataset
lengths = [
    count_chat_tokens(ex)
    for ex in train_data + val_data
]

print("\nTotal examples:", len(lengths))
print("Median tokens:", int(np.median(lengths)))
print("90th percentile:", int(np.percentile(lengths, 90)))
print("95th percentile:", int(np.percentile(lengths, 95)))
print("Maximum tokens:", max(lengths))

for limit in [1024, 1536, 2048]:
    truncated = sum(length > limit for length in lengths)
    print(f"Exceeding {limit} tokens: {truncated}/{len(lengths)}")

Tokens in one example: 843

Total examples: 726
Median tokens: 1075
90th percentile: 1348
95th percentile: 1444
Maximum tokens: 1955
Exceeding 1024 tokens: 436/726
Exceeding 1536 tokens: 20/726
Exceeding 2048 tokens: 0/726

In [ ]:

import json
import os
from transformers import AutoTokenizer

BASE = "/content/paperpilot_data_v2"
OUT = "/content/paperpilot_ready"
MODEL = "Qwen/Qwen2.5-0.5B-Instruct"

os.makedirs(OUT, exist_ok=True)
tokenizer = AutoTokenizer.from_pretrained(MODEL)

def load_jsonl(path):
    with open(path, encoding="utf-8") as f:
        return [json.loads(line) for line in f if line.strip()]

def prepare(ex):
    refs = "\n\n".join(
        f"Reference Paper {i+1}:\n{r}"
        for i, r in enumerate(ex["reference_abstracts"])
    )
    prompt = (
        "Write a coherent scientific related-work section. "
        "Synthesize relevant ideas across the supplied papers. "
        "Do not invent facts or citations.\n\n"
        f"Query Paper Abstract:\n{ex['input_abstract']}\n\n"
        f"Reference Papers:\n{refs}"
    )
    messages = [
        {"role": "system", "content": "You are a scientific writing assistant."},
        {"role": "user", "content": prompt}
    ]
    prompt_tokens = tokenizer.apply_chat_template(
        messages, tokenize=True, add_generation_prompt=True
    )
    target_tokens = tokenizer(
        ex["target_related_work"], add_special_tokens=False
    )["input_ids"]

    return {
        "paper_id": ex["paper_id"],
        "prompt": prompt,
        "target": ex["target_related_work"],
        "prompt_tokens": len(prompt_tokens),
        "target_tokens": len(target_tokens),
        "total_tokens": len(prompt_tokens) + len(target_tokens)
    }

for split in ["train", "validation"]:
    source = os.path.join(BASE, f"{split}.jsonl")
    assert os.path.exists(source), f"Source file missing: {source}"

    examples = load_jsonl(source)
    prepared = [prepare(ex) for ex in examples]

    with open(os.path.join(OUT, f"{split}.jsonl"), "w", encoding="utf-8") as f:
        for ex in prepared:
            f.write(json.dumps(ex, ensure_ascii=False) + "\n")

    print(f"{split}: {len(prepared)} examples prepared")

config = {
    "model_name": MODEL,
    "train_file": f"{OUT}/train.jsonl",
    "validation_file": f"{OUT}/validation.jsonl",
    "output_dir": "/content/paperpilot_model",
    "max_seq_length": 2048,
    "method": "LoRA",
    "lora_r": 8,
    "lora_alpha": 16,
    "lora_dropout": 0.05,
    "learning_rate": 0.0001,
    "num_train_epochs": 3,
    "per_device_train_batch_size": 1,
    "gradient_accumulation_steps": 8,
    "fp16": True,
    "seed": 42
}

with open(f"{OUT}/training_config.json", "w", encoding="utf-8") as f:
    json.dump(config, f, indent=2)

print("\nPrepared files:")
print(os.listdir(OUT))

train: 652 examples prepared
validation: 74 examples prepared

Prepared files:
['train.jsonl', 'training_config.json', 'validation.jsonl']

In [ ]:
from google.colab import drive
drive.mount("/content/drive")

import os
import shutil

source = "/content/paperpilot_ready"
destination = "/content/drive/MyDrive/PaperPilot/training_data"

os.makedirs(destination, exist_ok=True)

for filename in ["train.jsonl", "validation.jsonl", "training_config.json"]:
    shutil.copy2(
        os.path.join(source, filename),
        os.path.join(destination, filename)
    )

print("Backup complete:")
print(destination)
print(os.listdir(destination))

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Backup complete:
/content/drive/MyDrive/PaperPilot/training_data
['train.jsonl', 'validation.jsonl', 'training_config.json']

In [ ]:
%%writefile /content/drive/MyDrive/PaperPilot/training_data/train_lora.py
import os
import json
import torch

from datasets import load_dataset
from transformers import (
    AutoTokenizer,
    AutoModelForCausalLM,
    TrainingArguments,
    Trainer,
    DataCollatorForSeq2Seq,
)
from peft import LoraConfig, get_peft_model, TaskType

BASE = "/content/drive/MyDrive/PaperPilot/training_data"
MODEL_NAME = "Qwen/Qwen2.5-0.5B-Instruct"
OUTPUT_DIR = "/content/drive/MyDrive/PaperPilot/lora_model"
MAX_LENGTH = 2048

assert torch.cuda.is_available(), (
    "No GPU available. Do not start training until a GPU is available."
)

tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token

model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    torch_dtype=torch.float16,
)
model.config.use_cache = False

lora_config = LoraConfig(
    task_type=TaskType.CAUSAL_LM,
    r=8,
    lora_alpha=16,
    lora_dropout=0.05,
    target_modules=["q_proj", "k_proj", "v_proj", "o_proj"],
)
model = get_peft_model(model, lora_config)
model.print_trainable_parameters()

def load_jsonl(path):
    with open(path, encoding="utf-8") as f:
        return [json.loads(line) for line in f if line.strip()]

def tokenize_example(ex):
    messages = [
        {
            "role": "system",
            "content": "You are a careful scientific writing assistant."
        },
        {"role": "user", "content": ex["prompt"]},
    ]

    prompt_ids = tokenizer.apply_chat_template(
        messages,
        tokenize=True,
        add_generation_prompt=True,
    )
    target_ids = tokenizer(
        ex["target"],
        add_special_tokens=False,
    )["input_ids"] + [tokenizer.eos_token_id]

    input_ids = (prompt_ids + target_ids)[:MAX_LENGTH]
    labels = ([-100] * len(prompt_ids) + target_ids)[:MAX_LENGTH]

    return {
        "input_ids": input_ids,
        "attention_mask": [1] * len(input_ids),
        "labels": labels,
    }

train_raw = load_jsonl(os.path.join(BASE, "train.jsonl"))
val_raw = load_jsonl(os.path.join(BASE, "validation.jsonl"))

from datasets import Dataset

train_ds = Dataset.from_list([
    tokenize_example(ex) for ex in train_raw
])
val_ds = Dataset.from_list([
    tokenize_example(ex) for ex in val_raw
])

args = TrainingArguments(
    output_dir=OUTPUT_DIR,
    num_train_epochs=3,
    per_device_train_batch_size=1,
    per_device_eval_batch_size=1,
    gradient_accumulation_steps=8,
    learning_rate=1e-4,
    fp16=True,
    gradient_checkpointing=True,
    eval_strategy="epoch",
    save_strategy="epoch",
    logging_steps=10,
    save_total_limit=2,
    report_to="none",
    seed=42,
)

trainer = Trainer(
    model=model,
    args=args,
    train_dataset=train_ds,
    eval_dataset=val_ds,
    data_collator=DataCollatorForSeq2Seq(
        tokenizer=tokenizer,
        padding=True,
        label_pad_token_id=-100,
    ),
)

trainer.train()
trainer.save_model(OUTPUT_DIR)
tokenizer.save_pretrained(OUTPUT_DIR)

print("LoRA training complete. Model saved to:", OUTPUT_DIR)

Writing /content/drive/MyDrive/PaperPilot/training_data/train_lora.py

In [ ]:
import torch
import transformers
import datasets

print("GPU available:", torch.cuda.is_available())
if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))

print("PyTorch:", torch.__version__)
print("Transformers:", transformers.__version__)
print("Datasets:", datasets.__version__)

try:
    import peft
    print("PEFT:", peft.__version__)
except ImportError:
    print("PEFT: not installed")

GPU available: False
PyTorch: 2.11.0+cpu
Transformers: 5.18.0
Datasets: 4.8.5
PEFT: 0.21.1

In [1]:

%pip install -q "transformers==4.51.3" "datasets==3.6.0" "peft==0.15.2" "accelerate==1.6.0"

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.4/10.4 MB 41.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 491.5/491.5 kB 17.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 411.1/411.1 kB 10.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 354.7/354.7 kB 10.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 116.3/116.3 kB 4.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 193.6/193.6 kB 7.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 566.4/566.4 kB 21.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 146.7/146.7 kB 10.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 47.5 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
gradio 6.29.0 requires huggingface-hub<3.0,>=1.16.0, but you have huggingface-hub 0.36.2 which is incompatible.
diffusers 0.40.0 requires huggingface-hub<2.0,>=1.23.0, but you have huggingface-hub 0.36.2 which is incompatible.
gcsfs 2025.12.0 requires fsspec==2025.12.0, but you have fsspec 2025.3.0 which is incompatible.

In [2]:

import torch
import transformers
import datasets
import peft
import accelerate

print("GPU available:", torch.cuda.is_available())

if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))

print("PyTorch:", torch.__version__)
print("Transformers:", transformers.__version__)
print("Datasets:", datasets.__version__)
print("PEFT:", peft.__version__)
print("Accelerate:", accelerate.__version__)

WARNING:torchao.kernel.intmm:Warning: Detected no triton, on systems without Triton certain kernels will not work

GPU available: False
PyTorch: 2.11.0+cpu
Transformers: 4.51.3
Datasets: 3.6.0
PEFT: 0.15.2
Accelerate: 1.6.0

In [1]:

import torch

print("GPU available:", torch.cuda.is_available())

if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))
    print("CUDA version:", torch.version.cuda)
else:
    print("No GPU allocated. Do not start training.")

GPU available: True
GPU: Tesla T4
CUDA version: 13.0

In [2]:

from google.colab import drive
drive.mount("/content/drive")

import os
import torch
import transformers
import datasets
import peft
import accelerate

print("\n--- GPU ---")
print("Available:", torch.cuda.is_available())
print("PyTorch:", torch.__version__)
print("PyTorch CUDA build:", torch.version.cuda)

if torch.cuda.is_available():
    print("Device:", torch.cuda.get_device_name(0))
    print("GPU memory (GB):",
          round(torch.cuda.get_device_properties(0).total_memory / 1e9, 2))

print("\n--- Packages ---")
print("Transformers:", transformers.__version__)
print("Datasets:", datasets.__version__)
print("PEFT:", peft.__version__)
print("Accelerate:", accelerate.__version__)

print("\n--- PaperPilot files ---")
base = "/content/drive/MyDrive/PaperPilot/training_data"

for name in [
    "train.jsonl",
    "validation.jsonl",
    "training_config.json",
    "train_lora.py",
]:
    path = os.path.join(base, name)
    print(f"{name}: {'FOUND' if os.path.isfile(path) else 'MISSING'}")

Mounted at /content/drive

--- GPU ---
Available: True
PyTorch: 2.11.0+cu130
PyTorch CUDA build: 13.0
Device: Tesla T4
GPU memory (GB): 15.64

--- Packages ---
Transformers: 5.18.0
Datasets: 4.8.5
PEFT: 0.21.1
Accelerate: 1.15.0

--- PaperPilot files ---
train.jsonl: FOUND
validation.jsonl: FOUND
training_config.json: FOUND
train_lora.py: FOUND

In [3]:

%run /content/drive/MyDrive/PaperPilot/training_data/train_lora.py

config.json:   0%|          | 0.00/659 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/7.30k [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/2.78M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/1.67M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/7.03M [00:00<?, ?B/s]

[transformers] `torch_dtype` is deprecated! Use `dtype` instead!

model.safetensors: reconstructing file:   0%|          |  0.00B /  988MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/290 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/242 [00:00<?, ?B/s]

ImportError: Found an incompatible version of torchao. Found version 0.10.0, but only versions above 0.16.0 are supported

In [5]:

%pip uninstall -y torchao

Found existing installation: torchao 0.10.0
Uninstalling torchao-0.10.0:
  Successfully uninstalled torchao-0.10.0

In [1]:

from google.colab import drive
drive.mount("/content/drive")

%run /content/drive/MyDrive/PaperPilot/training_data/train_lora.py

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

[transformers] `torch_dtype` is deprecated! Use `dtype` instead!

Loading weights:   0%|          | 0/290 [00:00<?, ?it/s]

trainable params: 1,081,344 || all params: 495,114,112 || trainable%: 0.2184

TypeError: unsupported operand type(s) for +: 'BatchEncoding' and 'list'

In [2]:

path = "/content/drive/MyDrive/PaperPilot/training_data/train_lora.py"

with open(path, "r", encoding="utf-8") as f:
    script = f.read()

old = '''    target_ids = tokenizer(
        ex["target"],
        add_special_tokens=False,
    )["input_ids"] + [tokenizer.eos_token_id]'''

new = '''    target_ids = tokenizer(
        ex["target"],
        add_special_tokens=False,
    )["input_ids"] + [tokenizer.eos_token_id]

    prompt_ids = prompt_ids.tolist() if hasattr(prompt_ids, "tolist") else list(prompt_ids)'''

if old not in script:
    print("Could not find the exact code to patch. No changes made.")
else:
    script = script.replace(old, new, 1)
    with open(path, "w", encoding="utf-8") as f:
        f.write(script)
    print("Training script patched successfully.")

Training script patched successfully.

In [3]:

%run /content/drive/MyDrive/PaperPilot/training_data/train_lora.py

Loading weights:   0%|          | 0/290 [00:00<?, ?it/s]

trainable params: 1,081,344 || all params: 495,114,112 || trainable%: 0.2184

ArrowTypeError: Expected bytes, got a 'int' object

In [4]:

path = "/content/drive/MyDrive/PaperPilot/training_data/train_lora.py"

with open(path, "r", encoding="utf-8") as f:
    script = f.read()

old = '''train_ds = Dataset.from_list([
    tokenize_example(ex) for ex in train_raw
])
val_ds = Dataset.from_list([
    tokenize_example(ex) for ex in val_raw
])'''

new = '''from datasets import Features, Sequence, Value

features = Features({
    "input_ids": Sequence(Value("int32")),
    "attention_mask": Sequence(Value("int8")),
    "labels": Sequence(Value("int32")),
})

train_ds = Dataset.from_list(
    [tokenize_example(ex) for ex in train_raw],
    features=features,
)
val_ds = Dataset.from_list(
    [tokenize_example(ex) for ex in val_raw],
    features=features,
)'''

if old not in script:
    print("Expected code block not found; script unchanged.")
else:
    script = script.replace(old, new, 1)
    with open(path, "w", encoding="utf-8") as f:
        f.write(script)
    print("Dataset feature types added successfully.")

Dataset feature types added successfully.

In [5]:

%run /content/drive/MyDrive/PaperPilot/training_data/train_lora.py

Loading weights:   0%|          | 0/290 [00:00<?, ?it/s]

trainable params: 1,081,344 || all params: 495,114,112 || trainable%: 0.2184

ArrowTypeError: Expected bytes, got a 'int' object

In [6]:

path = "/content/drive/MyDrive/PaperPilot/training_data/train_lora.py"

with open(path, "r", encoding="utf-8") as f:
    script = f.read()

old = '    prompt_ids = prompt_ids.tolist() if hasattr(prompt_ids, "tolist") else list(prompt_ids)'

new = '''    if isinstance(prompt_ids, dict):
        prompt_ids = prompt_ids["input_ids"]
    if hasattr(prompt_ids, "tolist"):
        prompt_ids = prompt_ids.tolist()
    if prompt_ids and isinstance(prompt_ids[0], list):
        prompt_ids = prompt_ids[0]'''

if old not in script:
    print("Patch target not found. Script unchanged.")
else:
    script = script.replace(old, new, 1)
    with open(path, "w", encoding="utf-8") as f:
        f.write(script)
    print("Tokenization fix saved.")

Tokenization fix saved.

In [7]:

%run /content/drive/MyDrive/PaperPilot/training_data/train_lora.py

Loading weights:   0%|          | 0/290 [00:00<?, ?it/s]

trainable params: 1,081,344 || all params: 495,114,112 || trainable%: 0.2184

TypeError: unsupported operand type(s) for +: 'BatchEncoding' and 'list'

In [8]:

import re

path = "/content/drive/MyDrive/PaperPilot/training_data/train_lora.py"

with open(path, "r", encoding="utf-8") as f:
    script = f.read()

fixed_function = '''def tokenize_example(ex):
    messages = [
        {
            "role": "system",
            "content": "You are a careful scientific writing assistant."
        },
        {"role": "user", "content": ex["prompt"]},
    ]

    encoded_prompt = tokenizer.apply_chat_template(
        messages,
        tokenize=True,
        add_generation_prompt=True,
        return_dict=True,
    )

    # Always extract actual token IDs, never concatenate BatchEncoding objects.
    prompt_ids = encoded_prompt["input_ids"]
    if hasattr(prompt_ids, "tolist"):
        prompt_ids = prompt_ids.tolist()
    if prompt_ids and isinstance(prompt_ids[0], list):
        prompt_ids = prompt_ids[0]
    prompt_ids = [int(x) for x in prompt_ids]

    target_ids = tokenizer(
        ex["target"],
        add_special_tokens=False,
    )["input_ids"]
    target_ids = [int(x) for x in target_ids]
    target_ids.append(int(tokenizer.eos_token_id))

    input_ids = (prompt_ids + target_ids)[:MAX_LENGTH]
    labels = ([-100] * len(prompt_ids) + target_ids)[:MAX_LENGTH]

    return {
        "input_ids": input_ids,
        "attention_mask": [1] * len(input_ids),
        "labels": labels,
    }

'''

pattern = r"def tokenize_example\(ex\):.*?(?=\ntrain_raw = load_jsonl)"
updated, count = re.subn(
    pattern,
    lambda _: fixed_function,
    script,
    count=1,
    flags=re.S,
)

if count != 1:
    print("Function was not replaced. No file changes made.")
else:
    with open(path, "w", encoding="utf-8") as f:
        f.write(updated)
    print("Tokenization function replaced successfully.")

    # Verify the repaired function using one real training example.
    exec(
        fixed_function
        + '\n_test = tokenize_example(load_jsonl(os.path.join(BASE, "train.jsonl"))[0])'
        + '\nassert all(isinstance(x, int) for x in _test["input_ids"])'
        + '\nassert len(_test["input_ids"]) == len(_test["labels"])'
        + '\nprint("Test passed. Token count:", len(_test["input_ids"]))',
        globals(),
    )

Tokenization function replaced successfully.
Test passed. Token count: 837

In [9]:

%run /content/drive/MyDrive/PaperPilot/training_data/train_lora.py

Loading weights:   0%|          | 0/290 [00:00<?, ?it/s]

trainable params: 1,081,344 || all params: 495,114,112 || trainable%: 0.2184

LoRA training complete. Model saved to: /content/drive/MyDrive/PaperPilot/lora_model

In [10]:

import torch
from transformers import AutoTokenizer, AutoModelForCausalLM
from peft import PeftModel

BASE_MODEL = "Qwen/Qwen2.5-0.5B-Instruct"
ADAPTER_PATH = "/content/drive/MyDrive/PaperPilot/lora_model"

tokenizer = AutoTokenizer.from_pretrained(ADAPTER_PATH)

base_model = AutoModelForCausalLM.from_pretrained(
    BASE_MODEL,
    torch_dtype=torch.float16,
).to("cuda")

model = PeftModel.from_pretrained(base_model, ADAPTER_PATH)
model.eval()

prompt = """Given these research paper abstracts, write a concise
literature review comparing their methods, findings, and limitations.
Do not invent findings or citations.

Paper 1 abstract:
Transformer models improve text summarization by capturing long-range
context, but may require substantial computational resources.

Paper 2 abstract:
Parameter-efficient fine-tuning adapts pretrained language models
using a small number of trainable parameters, reducing training costs.

Paper 3 abstract:
Retrieval-augmented generation combines retrieved documents with
language generation to improve factual grounding.

Write one coherent literature-review paragraph."""

Loading weights:   0%|          | 0/290 [00:00<?, ?it/s]

In [11]:

messages = [
    {
        "role": "system",
        "content": "You are a careful scientific writing assistant. "
                   "Compare research findings accurately and do not invent citations."
    },
    {
        "role": "user",
        "content": prompt
    }
]

inputs = tokenizer.apply_chat_template(
    messages,
    tokenize=True,
    add_generation_prompt=True,
    return_tensors="pt",
    return_dict=True,
).to("cuda")

with torch.no_grad():
    outputs = model.generate(
        **inputs,
        max_new_tokens=250,
        do_sample=True,
        temperature=0.7,
        top_p=0.9,
        pad_token_id=tokenizer.eos_token_id,
    )

new_tokens = outputs[0][inputs["input_ids"].shape[1]:]
result = tokenizer.decode(new_tokens, skip_special_tokens=True)

print("PAPERPILOT — FINE-TUNED MODEL OUTPUT\n")
print(result)

PAPERPILOT — FINE-TUNED MODEL OUTPUT

The most recent transformer-based approaches, including the Transformer model @cite_7 , rely on efficient fine-tuning and retrieval augmentation. Retriever-based methods include the Transformer @cite_49 , which uses a small set of parameters to adapt a pre-trained language model for a specific task. These methods have been applied in various natural language processing tasks such as question answering @cite_50 and topic modeling @cite_5 .

In [12]:

import torch

# Find an example with three or four reference abstracts
example = next(
    ex for ex in val_raw
    if 3 <= len(ex["reference_abstracts"]) <= 4
)

messages = [
    {
        "role": "system",
        "content": "You are a careful scientific writing assistant. "
                   "Synthesize the supplied research papers into a coherent "
                   "literature review. Use only supported claims and do not "
                   "invent citations."
    },
    {
        "role": "user",
        "content": example["prompt"]
    }
]

inputs = tokenizer.apply_chat_template(
    messages,
    tokenize=True,
    add_generation_prompt=True,
    return_tensors="pt",
    return_dict=True,
).to("cuda")

model.eval()

with torch.no_grad():
    outputs = model.generate(
        **inputs,
        max_new_tokens=300,
        do_sample=False,
        pad_token_id=tokenizer.eos_token_id,
    )

generated = tokenizer.decode(
    outputs[0][inputs["input_ids"].shape[1]:],
    skip_special_tokens=True,
)

print("=== MODEL OUTPUT ===\n")
print(generated)

print("\n=== REFERENCE TARGET ===\n")
print(example["target"][:2500])

KeyError: 'reference_abstracts'

In [13]:

print("Available keys:", list(val_raw[0].keys()))
print("\nPrompt preview:")
print(val_raw[0].get("prompt", "No prompt field found")[:1000])
print("\nTarget preview:")
print(val_raw[0].get("target", "No target field found")[:500])

Available keys: ['paper_id', 'prompt', 'target', 'prompt_tokens', 'target_tokens', 'total_tokens']

Prompt preview:
Write a coherent scientific related-work section. Synthesize relevant ideas across the supplied papers. Do not invent facts or citations.

Query Paper Abstract:
Formal query generation aims to generate correct executable queries for question answering over knowledge bases (KBs), given entity and relation linking results. Current approaches build universal paraphrasing or ranking models for the whole questions, which are likely to fail in generating queries for complex, long-tail questions. In this paper, we propose SubQG, a new query generation approach based on frequent query substructures, which helps rank the existing (but nonsignificant) query structures or build new query structures. Our experiments on two benchmark datasets show that our approach significantly outperforms the existing ones, especially for complex questions. Also, it achieves promising performance with limited training data and noisy entity relation linking results.

Reference Papers:
Reference Paper 1:
In this pa

Target preview:
Semantic parsing-based approaches translate questions into formal queries using bottom up parsing @cite_5 or staged query graph generation @cite_12 . gAnswer @cite_15 @cite_1 builds up semantic query graph for question analysis and utilize subgraph matching for disambiguation. Recent studies combine parsing based approaches with neural networks, to enhance the ability for structure disambiguation. ConstraintQG ( ConstraintQG ), CQAEMNLP ( CQAEMNLP ) and SQG ( SQG ) build query graphs by staged q

In [14]:

import torch

# Select a held-out validation example
example = val_raw[0]

messages = [
    {
        "role": "system",
        "content": (
            "You are a careful scientific writing assistant. "
            "Synthesize the supplied research papers into a coherent "
            "related-work section. Use supported claims and preserve "
            "the supplied citation markers. Do not invent citations."
        ),
    },
    {
        "role": "user",
        "content": example["prompt"],
    },
]

inputs = tokenizer.apply_chat_template(
    messages,
    tokenize=True,
    add_generation_prompt=True,
    return_tensors="pt",
    return_dict=True,
).to("cuda")

model.eval()

with torch.no_grad():
    outputs = model.generate(
        **inputs,
        max_new_tokens=300,
        do_sample=False,
        pad_token_id=tokenizer.eos_token_id,
    )

generated = tokenizer.decode(
    outputs[0][inputs["input_ids"].shape[1]:],
    skip_special_tokens=True,
)

print("=== GENERATED LITERATURE REVIEW ===\n")
print(generated)

print("\n=== EXPECTED VALIDATION TARGET ===\n")
print(example["target"][:2500])

=== GENERATED LITERATURE REVIEW ===

The first attempt to address the problem of question answering over RDF was @cite_6 , where the authors proposed a semantic parser that uses a knowledge base to reduce the search space. They used a knowledge base to map each phrase to a predicate, and then used a bridging operation to generate additional predicates based on neighboring predicates. This approach is similar to the one used in @cite_17 . However, they did not consider the fact that the entities in the RDF graph may have multiple instances. For example, if the entity 'John' appears twice in the same sentence, the corresponding predicate should be generated twice.

=== EXPECTED VALIDATION TARGET ===

Semantic parsing-based approaches translate questions into formal queries using bottom up parsing @cite_5 or staged query graph generation @cite_12 . gAnswer @cite_15 @cite_1 builds up semantic query graph for question analysis and utilize subgraph matching for disambiguation. Recent studies combine parsing based approaches with neural networks, to enhance the ability for structure disambiguation. ConstraintQG ( ConstraintQG ), CQAEMNLP ( CQAEMNLP ) and SQG ( SQG ) build query graphs by staged query generation, and follow an encode-and-compare framework to rank candidate queries with neural networks. These approaches try to learn entire representations for questions with different query structures by using a single network. Thus, they may suffer from the lack of training data, especially for questions with rarely appeared structures. By contrast, our approach utilizes multiple networks to learn predictors for different query substructures, which can gain a stable performance with limited training data. Also, our approach does not require manually-written rules, and performs stably with noisy linking results.

In [15]:

import os
import json

output_dir = "/content/drive/MyDrive/PaperPilot/lora_model"

print("Model files:")
for name in os.listdir(output_dir):
    print("-", name)

# Inspect the saved training configuration
config_path = (
    "/content/drive/MyDrive/PaperPilot/training_data/training_config.json"
)

with open(config_path, "r", encoding="utf-8") as f:
    config = json.load(f)

print("\nTraining configuration:")
print(json.dumps(config, indent=2))

Model files:
- checkpoint-164
- checkpoint-246
- README.md
- adapter_model.safetensors
- adapter_config.json
- chat_template.jinja
- tokenizer_config.json
- tokenizer.json
- training_args.bin

Training configuration:
{
  "model_name": "Qwen/Qwen2.5-0.5B-Instruct",
  "train_file": "/content/paperpilot_ready/train.jsonl",
  "validation_file": "/content/paperpilot_ready/validation.jsonl",
  "output_dir": "/content/paperpilot_model",
  "max_seq_length": 2048,
  "method": "LoRA",
  "lora_r": 8,
  "lora_alpha": 16,
  "lora_dropout": 0.05,
  "learning_rate": 0.0001,
  "num_train_epochs": 3,
  "per_device_train_batch_size": 1,
  "gradient_accumulation_steps": 8,
  "fp16": true,
  "seed": 42
}

In [16]:

import os
import torch
from transformers import (
    AutoTokenizer,
    AutoModelForCausalLM,
    TrainingArguments,
    Trainer,
    DataCollatorForSeq2Seq,
)
from peft import PeftModel
from datasets import Dataset, Features, Sequence, Value

BASE = "/content/drive/MyDrive/PaperPilot/training_data"
ADAPTER = "/content/drive/MyDrive/PaperPilot/lora_model"
BASE_MODEL = "Qwen/Qwen2.5-0.5B-Instruct"
MAX_LENGTH = 2048

# Reuse the original saved validation data.
import json

with open(os.path.join(BASE, "validation.jsonl"), encoding="utf-8") as f:
    val_raw = [json.loads(line) for line in f if line.strip()]

tokenizer = AutoTokenizer.from_pretrained(ADAPTER)
if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token

base_model = AutoModelForCausalLM.from_pretrained(
    BASE_MODEL,
    torch_dtype=torch.float16,
).to("cuda")

model = PeftModel.from_pretrained(base_model, ADAPTER)
model.config.use_cache = False

def tokenize_example(ex):
    messages = [
        {"role": "system", "content": "You are a careful scientific writing assistant."},
        {"role": "user", "content": ex["prompt"]},
    ]
    enc = tokenizer.apply_chat_template(
        messages,
        tokenize=True,
        add_generation_prompt=True,
        return_dict=True,
    )
    prompt_ids = enc["input_ids"]
    if hasattr(prompt_ids, "tolist"):
        prompt_ids = prompt_ids.tolist()
    if prompt_ids and isinstance(prompt_ids[0], list):
        prompt_ids = prompt_ids[0]
    prompt_ids = [int(x) for x in prompt_ids]

    target_ids = tokenizer(
        ex["target"], add_special_tokens=False
    )["input_ids"]
    target_ids = [int(x) for x in target_ids] + [tokenizer.eos_token_id]

    input_ids = (prompt_ids + target_ids)[:MAX_LENGTH]
    labels = ([-100] * len(prompt_ids) + target_ids)[:MAX_LENGTH]

    return {
        "input_ids": input_ids,
        "attention_mask": [1] * len(input_ids),
        "labels": labels,
    }

features = Features({
    "input_ids": Sequence(Value("int32")),
    "attention_mask": Sequence(Value("int8")),
    "labels": Sequence(Value("int32")),
})

val_ds = Dataset.from_list(
    [tokenize_example(ex) for ex in val_raw],
    features=features,
)

args = TrainingArguments(
    output_dir="/content/paperpilot_eval",
    per_device_eval_batch_size=1,
    fp16=True,
    report_to="none",
)

trainer = Trainer(
    model=model,
    args=args,
    eval_dataset=val_ds,
    data_collator=DataCollatorForSeq2Seq(
        tokenizer=tokenizer,
        padding=True,
        label_pad_token_id=-100,
    ),
)

metrics = trainer.evaluate()
print("\nValidation results:")
print(metrics)

Loading weights:   0%|          | 0/290 [00:00<?, ?it/s]

Validation results:
{'eval_loss': 2.549776315689087}

In [17]:

import torch

model.eval()

for i, example in enumerate(val_raw[:5], start=1):
    messages = [
        {
            "role": "system",
            "content": (
                "You are a careful scientific writing assistant. "
                "Synthesize the supplied papers into a coherent related-work "
                "section. Use only supported claims and do not invent citations."
            ),
        },
        {"role": "user", "content": example["prompt"]},
    ]

    inputs = tokenizer.apply_chat_template(
        messages,
        tokenize=True,
        add_generation_prompt=True,
        return_tensors="pt",
        return_dict=True,
    ).to("cuda")

    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=220,
            do_sample=False,
            pad_token_id=tokenizer.eos_token_id,
        )

    generated = tokenizer.decode(
        outputs[0][inputs["input_ids"].shape[1]:],
        skip_special_tokens=True,
    )

    print(f"\n{'=' * 25} EXAMPLE {i} {'=' * 25}")
    print("\nGENERATED:\n", generated)
    print("\nREFERENCE:\n", example["target"][:1200])

========================= EXAMPLE 1 =========================

GENERATED:
 The above works mainly focus on the question answering task. @cite_6 proposed a semantic parser that learns from question-answer pairs. They take advantage of the fact that the same question can have multiple answers. However, they still rely on annotated logical forms, which is costly to obtain at large scale. @cite_18 proposed a semantic query graph to model the query intention in the natural language question in a structural way, based on which, RDF Q A is reduced to subgraph matching problem. More importantly, they solve the ambiguity of natural language questions at the time when matches of query are found. @cite_27 proposed a systematic framework to answer natural language questions over RDF repository (RDF Q A) from a graph data-driven perspective. They propose a semantic query graph to model the query intention in the natural language question in a structural way, based on which, RDF Q A is reduced to subgraph matching problem. More importantly, they resolve the ambiguity of natural language questions at the time when matches of query are found.

REFERENCE:
 Semantic parsing-based approaches translate questions into formal queries using bottom up parsing @cite_5 or staged query graph generation @cite_12 . gAnswer @cite_15 @cite_1 builds up semantic query graph for question analysis and utilize subgraph matching for disambiguation. Recent studies combine parsing based approaches with neural networks, to enhance the ability for structure disambiguation. ConstraintQG ( ConstraintQG ), CQAEMNLP ( CQAEMNLP ) and SQG ( SQG ) build query graphs by staged query generation, and follow an encode-and-compare framework to rank candidate queries with neural networks. These approaches try to learn entire representations for questions with different query structures by using a single network. Thus, they may suffer from the lack of training data, especially for questions with rarely appeared structures. By contrast, our approach utilizes multiple networks to learn predictors for different query substructures, which can gain a stable performance with limited training data. Also, our approach does not require manually-written rules, and performs stably with noisy linking results.

========================= EXAMPLE 2 =========================

GENERATED:
 The use of thumbnails has been widely studied in the context of multimedia presentations @cite_1 , where they are often used to highlight important content. A recent study @cite_10 examined the effectiveness of using thumbnails in web searches. They compared the performance of three different types of thumbnails: text-only summaries, text summaries combined with thumbnail previews, and text summaries combined with plain thumbnails. Their results showed that the combination of text summaries and thumbnail previews performed better than text-only summaries and plain thumbnails.

REFERENCE:
 Prior research shows that the presence of thumbnails in search results help people locate articles of interest online @cite_19 @cite_21 @cite_8 , particularly when paired with informative titles, text snippets, and URLs. Thumbnails are a particularly important signal of relevance when some links to articles have them and others do not. @cite_19 further showed that presenting thumbnails without accompanying text leads to worse search performance than simply presenting text without a thumbnail. Thumbnails also trigger behavior that would otherwise not occur in their absence. For instance, @cite_24 observed that when an email contains a link to a video file, more people click on the link when it is accompanied by a thumbnail.

========================= EXAMPLE 3 =========================

GENERATED:
 In recent years, researchers have explored ways to improve the usability of image thumbnails. @cite_40 used a combination of image extraction and image captioning to create image excerpts. They extracted the main object of interest from the image and then used a simple rule-based algorithm to select the best image excerpt. @cite_56 proposed a novel approach called image captioning to extract useful information about the image from its captions. The authors used a machine learning model to predict the relevance of the image to the query. @cite_79 proposed a system that uses a combination of image extraction and image captioning to create image excerpts.

REFERENCE:
 Other prior research has considered how to automatically generate thumbnails using photos and images appearing in the article, such as by cropping, resizing, or selecting the most salient excerpts from them @cite_5 @cite_30 . More recently, @cite_37 introduced an algorithm to select highly salient and evocative thumbnails for videos. As this research was conducted with generic images, we see our work as a step toward the automatic generation of visualization thumbnails. This first requires a better understanding of current practices in thumbnail design.

========================= EXAMPLE 4 =========================

GENERATED:
 @cite_4 @cite_6 @cite_7 @cite_8 @cite_9 @cite_10 @cite_11 @cite_12 @cite_13 @cite_14 @cite_15 @cite_16 @cite_17 @cite_18 @cite_19 @cite_20 @cite_21 @cite_22 @cite_23 @cite_24 @cite_25 @cite_26 @cite_27 @cite_28 @cite_29 @cite_30 @cite_31 @cite_32 @cite_33 @cite_34 @cite_35 @cite_36 @cite_37 @cite_38 @cite_39 @cite_40 @cite_41 @cite_42 @cite_43 @cite_44 @cite_45 @cite_46 @cite_47 @cite_48 @cite_49

REFERENCE:
 Most approaches on the 3D human motion retrieval have focused on developing hand crafted features to represent the skeleton sequences @cite_17 @cite_19 @cite_4 . In this section, we broadly categorize them by the method in which they engineer their descriptors.

========================= EXAMPLE 5 =========================

GENERATED:
 In recent years, there have been many works on 3D human motion indexing and retrieval @cite_47 @cite_6 @cite_8 . @cite_47 proposed a deep learning based method to extract the deep signatures from the skeleton data. They utilized a CNN to encode the joint positions and performed a hierarchical clustering to group the joints into different categories. @cite_8 proposed a deep learning based method to extract the deep signatures from the skeleton data. They utilized a CNN to encode the joint positions and performed a hierarchical clustering to group the joints into different categories. Both methods require a lot of computational resources and hence cannot be applied to real-time streaming data.

REFERENCE:
 For the task of retrieval, @cite_2 proposed a simple auto-encoder that captures high-level features. However, their model doesn't explicitly use a temporal construct for motion data. Primarily, learnable representations from 3D motion data have been used for other tasks. @cite_18 @cite_14 are a few amongst many who used deep learning models for 3D motion recognition. Similarly, @cite_9 adopts a unidirectional LSTM to encode the skeleton frames within the hidden network states and learn what subsequences of encoded frames belong to the specified action classes.

In [18]:

import torch

model.eval()

for i, example in enumerate(val_raw[:5], start=1):
    messages = [
        {
            "role": "system",
            "content": (
                "You are PaperPilot, an academic literature-review assistant. "
                "Write a concise related-work passage based only on the "
                "research papers supplied in the prompt. Discuss their actual "
                "methods, findings, and limitations where supported. Do not "
                "introduce unrelated topics, invent study details, or repeat "
                "the same point. Use citation markers only when supported by "
                "the supplied material. If information is missing, omit it."
            ),
        },
        {"role": "user", "content": example["prompt"]},
    ]

    inputs = tokenizer.apply_chat_template(
        messages,
        tokenize=True,
        add_generation_prompt=True,
        return_tensors="pt",
        return_dict=True,
    ).to("cuda")

    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=180,
            do_sample=False,
            repetition_penalty=1.15,
            no_repeat_ngram_size=4,
            pad_token_id=tokenizer.eos_token_id,
            eos_token_id=tokenizer.eos_token_id,
        )

    generated = tokenizer.decode(
        outputs[0][inputs["input_ids"].shape[1]:],
        skip_special_tokens=True,
    )

    print(f"\n--- EXAMPLE {i} ---\n")
    print(generated)

--- EXAMPLE 1 ---

The above works mainly rely on the premise that the entities and relations between them have been pre-processed into a structured format such as RDF graphs @cite_6 . However, these approaches do not consider the fact that the user may want to ask about multiple things simultaneously. For example, they might want to know what kind of food people like best, or how many times someone likes a particular type of food. This leads us to develop a new approach called SubQG @cite_7 , which builds query structure hierarchies based on frequent patterns.

--- EXAMPLE 2 ---

The use of thumbnails has been widely studied in the context of multimedia content @cite_1 , including the creation of visually rich summaries of videos @cite_2 . A recent study @cite_3 examined the effectiveness of using thumbnails in web searches. They compared the usefulness of various kinds of thumbnails in web search result pages, finding that the inclusion of text summaries improved the accuracy of predictions relative to those generated solely by text alone. Another study @cite _10 explored the relationship between the presence of thumbnails and the performance of web search results, concluding that the addition of thumbnails improves the accuracy of search results but does so at the cost of increased processing time.

--- EXAMPLE 3 ---

In recent years, researchers have explored ways to improve the usability of image-based thumbnails @cite_4 , including adding captions @cite_6 , enhancing the visual appearance of thumbnails @cite _5 , and incorporating additional metadata about the source of the image @cite _7 . These approaches aim at improving the overall experience of viewing images, rather than focusing solely on the visual aspect of the image itself.

--- EXAMPLE 4 ---

@cite_4 @cite_6 @cite_7 @cite_8 @cite_9 @cite_10 @cite_2 @cite_3 @cite_5 @cite_4 .

--- EXAMPLE 5 ---

In @cite_4 , authors proposed a deep CNN encoder-decoder system to extract the key points from the skeleton images. They showed that the extracted keypoints could be used to generate a new set of skeleton image pairs. In @cite_6 , authors presented a deep learning based algorithm to identify joints and compute the corresponding pose parameters. In @ref_7 , authors introduced a deep learning framework to recover the skeleton from video sequence.

In [19]:

import re

def assess_output(text):
    words = re.findall(r"\b[\w'-]+\b", text)
    citations = re.findall(r"@cite[_ ]?\d+", text)
    unique_words = set(w.lower() for w in words)

    citation_ratio = len(citations) / max(len(words), 1)
    diversity = len(unique_words) / max(len(words), 1)

    issues = []
    if len(words) < 40:
        issues.append("too short")
    if citation_ratio > 0.20:
        issues.append("citation spam")
    if diversity < 0.35 and len(words) > 50:
        issues.append("low vocabulary diversity")

    return {
        "word_count": len(words),
        "citation_count": len(citations),
        "citation_ratio": round(citation_ratio, 3),
        "vocabulary_diversity": round(diversity, 3),
        "issues": issues or ["no obvious surface-level issue"],
    }

# Replace these sample strings with your five complete generated outputs.
outputs = [
    "PASTE EXAMPLE 1",
    "PASTE EXAMPLE 2",
    "PASTE EXAMPLE 3",
    "PASTE EXAMPLE 4",
    "PASTE EXAMPLE 5",
]

for i, output in enumerate(outputs, 1):
    print(f"Example {i}:", assess_output(output))

Example 1: {'word_count': 3, 'citation_count': 0, 'citation_ratio': 0.0, 'vocabulary_diversity': 1.0, 'issues': ['too short']}
Example 2: {'word_count': 3, 'citation_count': 0, 'citation_ratio': 0.0, 'vocabulary_diversity': 1.0, 'issues': ['too short']}
Example 3: {'word_count': 3, 'citation_count': 0, 'citation_ratio': 0.0, 'vocabulary_diversity': 1.0, 'issues': ['too short']}
Example 4: {'word_count': 3, 'citation_count': 0, 'citation_ratio': 0.0, 'vocabulary_diversity': 1.0, 'issues': ['too short']}
Example 5: {'word_count': 3, 'citation_count': 0, 'citation_ratio': 0.0, 'vocabulary_diversity': 1.0, 'issues': ['too short']}

In [20]:

import re
import torch

def assess_output(text):
    words = re.findall(r"\b[\w'-]+\b", text)
    citations = re.findall(r"@cite[_ ]?\d+", text)
    unique_words = set(w.lower() for w in words)

    issues = []
    if len(words) < 40:
        issues.append("too short")
    if len(citations) / max(len(words), 1) > 0.20:
        issues.append("citation spam")
    if len(words) > 50 and len(unique_words) / len(words) < 0.35:
        issues.append("low vocabulary diversity")

    return {
        "word_count": len(words),
        "citation_count": len(citations),
        "issues": issues or ["no obvious surface-level issue"],
    }

model.eval()
results = []

for i, example in enumerate(val_raw[:5], start=1):
    messages = [
        {
            "role": "system",
            "content": (
                "You are PaperPilot, an academic writing assistant. "
                "Write a concise related-work section based on the supplied "
                "research papers. Stay on topic, avoid unsupported details, "
                "and do not invent citations."
            ),
        },
        {"role": "user", "content": example["prompt"]},
    ]

    inputs = tokenizer.apply_chat_template(
        messages,
        tokenize=True,
        add_generation_prompt=True,
        return_tensors="pt",
        return_dict=True,
    ).to("cuda")

    with torch.no_grad():
        output = model.generate(
            **inputs,
            max_new_tokens=180,
            do_sample=False,
            repetition_penalty=1.15,
            no_repeat_ngram_size=4,
            pad_token_id=tokenizer.eos_token_id,
            eos_token_id=tokenizer.eos_token_id,
        )

    text = tokenizer.decode(
        output[0][inputs["input_ids"].shape[1]:],
        skip_special_tokens=True,
    )

    result = assess_output(text)
    results.append(result)

    print(f"\n--- Example {i} ---")
    print(text)
    print("Surface checks:", result)

print("\n--- Summary ---")
print("Examples generated:", len(results))
print("Flagged for surface issues:", sum(bool(r["issues"] != ["no obvious surface-level issue"]) for r in results))

--- Example 1 ---
The above works mainly aim to reduce the complexity of the original question-answering task into simpler tasks such as querying entities and relations. However, they all rely heavily on the annotation of logical forms @cite_6 . For example, @cite_7 uses a knowledge base to represent the query intent and then reduces the search space through a combination of top-k scoring and greedy strategy. Similarly, @cite _8 builds a semantic query-graph to match the query with the corresponding predicate sequence. This requires annotating each sentence separately.
Surface checks: {'word_count': 84, 'citation_count': 2, 'issues': ['no obvious surface-level issue']}

--- Example 2 ---
The use of thumbnails has been widely studied in various contexts @cite_1 , including social media @cite_2 . A recent study @cite_3 examined the effectiveness of using thumbnails in web searches. They compared the usefulness of thumbnail previews with those of traditional text-based summaries and showed that thumbnail previews performed worse than text summaries when searching for information on Wikipedia. Another study @cite _10 explored the impact of thumbnail previews on the performance of web search results and concluded that thumbnail previews did not improve the accuracy of the search results at all.
Surface checks: {'word_count': 91, 'citation_count': 3, 'issues': ['no obvious surface-level issue']}

--- Example 3 ---
In recent years, researchers have explored ways to improve the usability of image-based summaries @cite_4 , including adding captions @cite_6 , generating image excerpts @cite_7 , and applying machine learning algorithms @cite_9 . These approaches aim at improving the readability of image summaries while still retaining some useful information about the source material.
Surface checks: {'word_count': 49, 'citation_count': 4, 'issues': ['no obvious surface-level issue']}

--- Example 4 ---
@cite_4 @cite_6 @cite_7 @cite_8 @cite_9 @cite_10 @cite_2 @cite_3 @cite_5 @cite_4 , among others, have been focused on learning representations for human motion data. These works mainly focus on the following issues: how to represent the motion data? How to select the most informative features? What kind of loss functions should be used? And what kind of metrics should be used to compare the retrieved motions?
Surface checks: {'word_count': 64, 'citation_count': 10, 'issues': ['no obvious surface-level issue']}

--- Example 5 ---
In recent years, there have been many works focused on the application of deep learning techniques to human motion processing @cite_47 , @cite_68 . These studies mainly aim at improving the performance of existing algorithms while reducing computational costs. For instance, @cite_9 proposed a deep CNN encoder-decoder system to extract the key points from the video sequence. They showed that the extracted keypoints could be used to improve the performance of the motion classification algorithm. Another work @cite_10 introduced a deep CNN to generate a set of descriptors for each person's skeleton. Their main contribution was to develop a new loss function to train the deep CNNs. However, the authors did not consider the effect of the input image size on the performance of their model. Furthermore, the authors considered the input images were already preprocessed (e.g., color normalized) before applying the deep CNN. Therefore
Surface checks: {'word_count': 144, 'citation_count': 4, 'issues': ['no obvious surface-level issue']}

--- Summary ---
Examples generated: 5
Flagged for surface issues: 0

In [21]:

import re

def assess_output(text):
    words = re.findall(r"\b[\w'-]+\b", text)
    citations = re.findall(r"@cite\s*_?\s*\d+", text)
    issues = []

    # Citation density
    citation_ratio = len(citations) / max(len(words), 1)
    if len(citations) >= 8 or citation_ratio > 0.12:
        issues.append("citation-heavy output")

    # Very short or incomplete output
    if len(words) < 40:
        issues.append("too short")

    if text.rstrip().endswith(("Therefore", "However", "Furthermore", "because")):
        issues.append("possibly incomplete ending")

    # Repeated sentences
    sentences = [
        s.strip().lower()
        for s in re.split(r"[.!?]+", text)
        if len(s.strip()) > 20
    ]
    if len(sentences) != len(set(sentences)):
        issues.append("repeated sentences")

    return {
        "word_count": len(words),
        "citation_count": len(citations),
        "citation_ratio": round(citation_ratio, 3),
        "issues": issues or ["no obvious surface-level issue"],
    }